# System prompt used to detect and analyze vulnerabilities in PRs or single files
JCA_ANALYSIS_SYSTEM_PROMPT = (
    "Analyze the provided Java source code and detect all Direct and Indirect (dynamically) occurrences of cryptographic initialization and parameter handling."
    "In particular, please identify and list the following:\n"   
    "1. Direct Calls:\n"
    "   1. Cipher.getInstance(...).\n"
    "   2. New SecretKeySpec(...).\n"
    "   3. New PBEKeySpec(...) and new PBEParameterSpec(...).\n"
    "   4. KeyGenerator.getInstance(...) and SecretKeyFactory.getInstance(...).\n"
    "   5. New IvParameterSpec(...).\n"
    "   6. KeyStore.getInstance(...).\n"
    "2. Indirect Cryptographic Instantiations: Detect any method calls or dynamic mechanisms (for example, helper methods) "
    "that ultimately return an instance of a JCA object corresponding to the above patterns. "
    "This includes cases where the cryptographic object is not instantiated inline, "
    "but is returned from a function call, "
    "e.g., final IvParameterSpec iv = genIv(...);, where genIv(...) returns an IvParameterSpec.\n"
    "Output Requirement: For each detected occurrence answer the 8 following points:\n"
    "1- The type of cryptographic object.\n"
    "2- CallType: Indirect or Direct.\n"
    "3- The exact code snippet.\n"
    "4- Location: if found in one location (method name and line number if available), or in multiple locations.\n"
    "5- Vulnerability type:\n"
    "   1. The type of the Vulnerability:\n"
    "      a) Weak Symmetric Encryption Algorithms (e.g., DES, Blowfish, RC4, RC2, IDEA).\n"
    "      b) Weak Encryption Mode (ECB).\n"
    "      c) Insecure Asymmetric Ciphers (RSA with keysize<1024).\n"
    "      d) hardcoded or constant cryptographic keys in SecretKeySpec.\n"
    "      e) Static Salt for key derivation in PBEKeySpec or PBEParameterSpec.\n"
    "      f) Hardcoded or constant passwords in PBEKeySpec.\n"
    "      g) iteration count < 1000 in PBEKeySpec or PBEParameterSpec.\n"
    "      h) weak Random function for generating secret key or Predictable seed instead of SecureRandom.\n"
    "      i) Hardcoded or Constant IV.\n"
    "      j) Hardcoded or Constant Password in KeyStore.\n"
    "      k) broken hash functions (SHA1, MD2, MD5, ...).\n"
    "      l) constant seed in SecureRandom.\n"
    "   2. If there is not any Vulnerability, type is secure.\n"
    "   3. If the content of the JCA API method is missing, type is More Information is Needed.\n"                       
    "6- Severity: If Indirect calltype, print Undefined.\n"
    "   If direct call type: High with a CVSS score above 8.0 or those that allow remote code execution. "
    "Medium with a CVSS score between 5.0 and 8.0 or that requires local access for exploitation. "
    "Low with a CVSS score between 5.0 and 1.0. Secure with CVSS score less than 1.0.\n"
    "7- Correction: How to correct the Vulnerability if found, why it is secure, or why we need more information.\n"
    "8- JCA Execution: Answer the following questions:\n"
    "   1. The call chain leading to JCA instantiations.\n"
    "   2. Whether a default algorithm is stored in a class member and used later in the JCA instantiations.\n"
    "   3. Whether conditions directly affect the source value passed to JCA instantiation. The source when the condition is true versus when it is false.\n"
    "   4. Identify the classes directly involved in cryptographic logic, "
    "including the primary class where cryptographic objects are instantiated "
    "and any helper or utility classes that contribute to these instantiations, "
    "and the driver class (Ignore any frameworks that simply execute the cryptographic routines) that executes the cryptographic routines."
)

def get_jca_pr_analysis_prompt(combined_code: str) -> str:
    """Generates the user prompt for analyzing a PR without an issue."""
    return (
        f"Analyze the following combined Java code from the PR:\n\n{combined_code}\n\n"
        "Return only a JSON array."
    )

